public abstract class Shape { //abstract class...

    //abstract methods here...
    public abstract String getName();
    public abstract double getArea();
}

abstract class Shape2D extends Shape { //abstract class...
}

abstract class Shape3D { //abstract class...
    public abstract double getVolume(); //abstract method...
}