import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TaskItemTest {

    //TITLE
    //fails to create...
    @Test
    public void TestCreateTaskItemFailsWithInvalidTitle() {
        //test goes here...
    }

    //successfully creates...
    @Test
    public void TestCreateTaskItemSucceedsWithValidTitle() {
        //test goes here...
    }

    //fails to set...
    @Test
    public void TestSetTaskItemFailsWithInvalidTitle() {
        //test goes here...
    }

    //successfully sets...
    @Test
    public void TestSetTaskItemSucceedsWithValidTitle() {
        //test goes here...
    }

    //DUE DATE
    //fails to create due date of non-int values...
    @Test
    public void TestCreateTaskItemFailsWithInvalidDueDate1() {
        //test goes here...
    }

    //fails to create due date of incorrectly formatted due date...
    @Test
    public void TestCreateTaskItemFailsWithInvalidDueDate2() {
        //test goes here...
    }

    //fails to create due date of invalid month...
    @Test
    public void TestCreateTaskItemFailsWithInvalidDueDate3() {
        //test goes here...
    }

    //fails to create due date of invalid day...
    @Test
    public void TestCreateTaskItemFailsWithInvalidDueDate4() {
        //test goes here...
    }

    //successfully creates...
    @Test
    public void TestCreateTaskItemSucceedsWithValidDueDate() {
        //test goes here...
    }

    //fails to set due date to non-int values...
    @Test
    public void TestSetTaskItemFailsWithInvalidDueDate1() {
        //test goes here...
    }

    //fails to set due date to incorrectly formatted due date...
    @Test
    public void TestSetTaskItemFailsWithInvalidDueDate2() {
        //test goes here...
    }

    //fails to set due date to invalid month...
    @Test
    public void TestSetTaskItemFailsWithInvalidDueDate3() {
        //test goes here...
    }

    //fails to set due date to invalid day...
    @Test
    public void TestSetTaskItemFailsWithInvalidDueDate4() {
        //test goes here...
    }

    //successfully sets...
    @Test
    public void TestSetTaskItemSucceedsWithValidDueDate() {
        //test goes here...
    }
}